### ISSUE TITLE
Bullseye?

### ISSUE THREAD

**Issue by sydb** [aaknitt/voxcall#12]
At first glance, this software looks like it is _exactly_ what I am looking for. However, my Raspberry Pi runs bullseye (11), not buster (10). Is that going to be a problem?

Also, if I may ask what is perhaps a really dumb question, or at least one that demonstrates my complete lack of understanding of anything audio:

The instructions say “Use a cheap USB sound card as the audio input”. I don’t actually know what a sound card is. Is [this](https://www.amazon.com/Sabrent-External-Adapter-Windows-AU-MMSA/dp/B00IRVQ0F8) the sort of thing I should be looking for? (Well, if that is the right thing, I don’t have to look, I have one. :-)

**Comment by JoshCodeStuff** [comment]
> At first glance, this software looks like it is exactly what I am looking for. However, my Raspberry Pi runs bullseye (11), not buster (10). Is that going to be a problem?

It should work fine!

> Use a cheap USB sound card as the audio input”. I don’t actually know what a sound card is. Is [this](https://www.amazon.com/Sabrent-External-Adapter-Windows-AU-MMSA/dp/B00IRVQ0F8) the sort of thing I should be looking for? (Well, if that is the right thing, I don’t have to look, I have one. :-)


That's exactly what you need! Just bridge the in and outputs of that little USB with a 3.5mm male to male cable.

**Comment by sydb** [comment]
Thank you for the information! I tried, but no dice. (Scanner audio out is connected to cable that ends in 3.5mm male which is plugged into USB which is plugged into USB hub which is plugged into Rasberry Pi. I know USB hub is working because keyboard is also plugged into it. :-)
The log.txt says:
~~~
2023-06-22 13:57:06,941 - ERROR - Got exception on main handler
Traceback (most recent call last):
  File "voxcall.py", line 233, in start_audio_stream
  File "pyaudio.py", line 750, in open
  File "pyaudio.py", line 441, in __init__
OSError: [Errno -9997] Invalid sample rate
~~~
I do not really speak Python, but at first glance it looks like the rate is set to 22050 on source line 208.

BTW, I am not trying to use the Broadcastify or rdio-scanner features at all. Just want audio files. The console has 1,798 lines of messages on startup of `./voxcall/voxcall`, many of which look scary.

Any thoughts?

**Comment by aaknitt** [comment]
> Thank you for the information! I tried, but no dice. (Scanner audio out is connected to cable that ends in 3.5mm male which is plugged into USB which is plugged into USB hub which is plugged into Rasberry Pi. I know USB hub is working because keyboard is also plugged into it. :-) The log.txt says:
> 
> ```
> 2023-06-22 13:57:06,941 - ERROR - Got exception on main handler
> Traceback (most recent call last):
>   File "voxcall.py", line 233, in start_audio_stream
>   File "pyaudio.py", line 750, in open
>   File "pyaudio.py", line 441, in __init__
> OSError: [Errno -9997] Invalid sample rate
> ```
> 
> I do not really speak Python, but at first glance it looks like the rate is set to 22050 on source line 208.
> 
> BTW, I am not trying to use the Broadcastify or rdio-scanner features at all. Just want audio files. The console has 1,798 lines of messages on startup of `./voxcall/voxcall`, many of which look scary.
> 
> Any thoughts?

You need to select 'pulse' as the audio source on the Raspberry Pi, not the actual USB sound card.  I know it's counter-intuitive, but the pulse audio sound system does the sample rate conversion so that voxcall can get the audio from the sound card at the rate that it needs.

**Comment by sydb** [comment]
Thank you for the response!
Unfortunately, I am still not able to record. I set to “pulse”, saved & exited, and re-launched. I then watched the voxcall GUI window while there was _definitely_ radio traffic, and the Audio Level bar on the R did not twitch.
If it is helpful (or at least interesting), take a look at the [messages I see on the console on starting voxcall](https://bauman.zapto.org/~syd/temp/transfer/voxcall_startup_console_2023-07-02T10:31.txt).
I have also tried cloning the git repo to the Raspberry Pi, installing pyaudio, and running via `python ./voxcall.py`. Furthermore, I set the scanner to the weather (162.4 MHz) so I do not have to wait for a transmission, and tested the sound out port on the scanner (by plugging in an external speaker). Still no movement of Audio Level bar, nor any output I have found.

**Comment by sydb** [comment]
DISREGARD

I became suspicious about the connection and tried moving the USB to a different port on the hub (and wiggled all the connections as I went), and presto! Getting audio files saved now.
Thank you _very_ much, I think I am gonna _love_ this!
