### ISSUE TITLE
OpenMHZ

### ISSUE THREAD

**Issue by JoshCodeStuff** [aaknitt/voxcall#14]
Hey there! I have been using VoxCall for awhile for a BCFY calls feed, however I recetly found OpenMHZ and I love it's open source nature so I was wondering if there is OpenMHZ support planned for VoxCall? 

Thanks!
~Josh

**Comment by aaknitt** [comment]
OpenMHz support is available to test on this branch:
https://github.com/aaknitt/voxcall/tree/openmhz

**Comment by JoshCodeStuff** [comment]
> OpenMHz support is available to test on this branch: https://github.com/aaknitt/voxcall/tree/openmhz

I have given it a try, and it is working right out of the box! Fantastic work!
