### ISSUE TITLE
Linux/PI version missing config options

### ISSUE THREAD

**Issue by mattjfrank** [aaknitt/voxcall#15]
I'm not seeing any options in the Pi version to set the URL etc. It appears to be only for the broadcastify version.

**Comment by aaknitt** [comment]
Can you provide any additional detail?  Are you using the 1.1.0 release from here?
https://github.com/aaknitt/voxcall/releases/tag/1.1.0

If so, what are you seeing on the GUI?  Can you provide a screenshot?

**Comment by mattjfrank** [comment]
I am using the latest version from the above link for raspberry pi the config has no options for sending the data to rdio-scanner, like the URL etc. It's all predefined for broadcastify.

[Section1]
bcfy_systemid = 
radiofreq = 
bcfy_apikey = 
bcfy_slotid = 
audio_dev_index = 1
record_threshold = 47
vox_silence_time = 2
in_channel = mono
saveaudio = 0

**Comment by mattjfrank** [comment]
> Can you provide any additional detail? Are you using the 1.1.0 release from here? https://github.com/aaknitt/voxcall/releases/tag/1.1.0
> 
> If so, what are you seeing on the GUI? Can you provide a screenshot?
