### ISSUE TITLE
Suggestion: Can you make so it can do an API upload to Rdio-Scanner?

### ISSUE THREAD

**Issue by JayManCanada6014** [aaknitt/voxcall#4]
This has an API upload feature can your app be made to support both?  
https://github.com/chuot/rdio-scanner

**Comment by aaknitt** [comment]
Looks like it should be possible.  I'll try to get an instance of rdio-scanner up and running here to test against.  No promises on timeline.

**Comment by JayManCanada6014** [comment]
> Looks like it should be possible. I'll try to get an instance of rdio-scanner up and running here to test against. No promises on timeline.

I can give you access to mine as well, different API key on its own system.

**Comment by aaknitt** [comment]
I've created a branch that adds support here:

https://github.com/aaknitt/voxcall/tree/rdio-scanner

I haven't built binary executables yet but if you want to play with the python source to test, go for it.  Once it's fully vetted I'll create binaries, update the documentation, and merge to the main branch.

**Comment by JayManCanada6014** [comment]
> I've created a branch that adds support here:
> 
> https://github.com/aaknitt/voxcall/tree/rdio-scanner
> 
> I haven't built binary executables yet but if you want to play with the python source to test, go for it. Once it's fully vetted I'll create binaries, update the documentation, and merge to the main branch.

It has been working well.   As I posted on Gitter.  it's not saving configs right now and the URL for Rdio-Scanner you had to put in the full URL to the API, might be something to reference.

**Comment by JayManCanada6014** [comment]
Still going strong.  @aaknitt   I think you are good other than the config not saving.   It seems stable.

**Comment by aaknitt** [comment]
@JayManCanada6014 the config file is saving correctly for me.  Are you closing the program using the "Save & Exit" button or the "X" in the upper right?  "X" will not save, only "Save & Exit".

**Comment by JayManCanada6014** [comment]
@aaknitt  When I press save, this shows up in the shell.  

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "C:\voxcall-rdio-scanner\voxcall.py", line 498, in saveconfigdata
    config.set('Section1','audio_dev_index',str(input_device_indices[input_device.get()]))
  File "C:\Program Files\Python39\lib\configparser.py", line 1201, in set
    super().set(section, option, value)
  File "C:\Program Files\Python39\lib\configparser.py", line 902, in set
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'Section1'

and nothing is written to the config.cfg BUT it does update the last modified timestamp.

**Comment by aaknitt** [comment]
Thanks.  Just pushed an update that should fix this.  Try grabbing the latest from the rdio-scanner branch and see how it works.

**Comment by JayManCanada6014** [comment]
Yes it is working now. Thanks.

**Comment by aaknitt** [comment]
Created Windows and Pi binaries and merged to master.
